Repository AY2425S2-CS2103T-T14-1/tp, pull requests merged in 2025-04, with the labels that each got.

#153 Make person fields optional
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/ReadOnlyCommandHistory.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Nickname.java
  src/main/java/seedu/address/model/person/Notes.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Relationship.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializable.java
  src/main/java/seedu/address/storage/JsonStorage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/RelationshipTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonCommandHistoryStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableCommandHistoryTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.Medium, alpha-bug

#175 Remove auto-capitalization for words with /
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: type.Bug, severity.Low, alpha-bug

#186 Update UNKNOWN_COMMAND message for better clarity
  src/main/java/seedu/address/logic/Messages.java
Labels: severity.VeryLow

#188 Fix undo after clear
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
Labels: type.Bug, alpha-bug

#187 Fix find then edit flow
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Bug, severity.Low, alpha-bug

#176 Raise more specific error messages for name
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, severity.Low, alpha-bug

#194 Add more helpful error messages for add
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Bug, severity.Low, alpha-bug

#195 Update storage uml
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
Labels: type.Task

#157 Possibly Unclear Undo Success Message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/person/NameSimilarPredicateTest.java
Labels: severity.VeryLow

#172 Undo does not restore the original order in the displayed list
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: severity.Low, alpha-bug

#174 Update Documentation
  docs/DeveloperGuide.md
  docs/diagrams/UndoSequenceDiagramProposed.puml
Labels: type.Task

#178 Fix email regex to ensure proper validation
  src/main/java/seedu/address/model/person/Email.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: severity.Medium, alpha-bug

#191 Display name and nickname side by side
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug

#199 Add example command for error
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.Low, alpha-bug

#203 Miscellaneous help window format issues
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, severity.Low

#279 Fix bugs reported in PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Bug

#281 Fix PE-D Tester B Bugs
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/person/Relationship.java
Labels: type.Bug

#295 Fix minor bugs in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#308 Update help window
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug

#315 Fix identified DG bugs
  docs/DeveloperGuide.md
Labels: type.Bug
